spring.application.name=matchme

# jdbc driver implementation will be used -> specific implementation (postgresql) -> the place db is located -> db name
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme_db

# super admin credentials which are used in all operations with db
spring.datasource.username=admin
spring.datasource.password=secret


# tells spring that tables should be created on app start or update tables if entities are changed.
spring.jpa.hibernate.ddl-auto=update








