spring.application.name=matchme

# jdbc driver implementation will be used -> specific implementation (postgresql) -> the place db is located -> db name
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme_db
#spring.datasource.driver-class-name=org.postgresql.Driver

# redis credentials for a spring
spring.data.redis.host=matchme-redis
spring.data.redis.port=6379 


# super admin credentials which are used in all operations with db
spring.datasource.username=admin
spring.datasource.password=secret

# JWT token config
app.jwt.secretKeyBase=46K!pzdO9IXCfaGS4m$GxyEqFKXLe1lzW4r3pCzD3%xNtQI67COwiXBiNNfaJke!
app.jwt.expirationTime=86400000


## Flyway
#spring.flyway.enabled=true
#spring.fly

# telling hibernate it can validate scheme only but the creation of tables will be managed by flyway
spring.jpa.hibernate.ddl-auto=validate

# logs tracking in case something went wrong with unauthorized requests
logging.level.org.springframework.security=TRACE

